- job:
    description: null
    disabled: false
    name: '4. Full Cloud - Configure'
    parameters:
    - string:
        default: ''
        description: Name of slave node to run this job on
        name: SLAVE_NODE_NAME
    - choice:
        choices:
        - amd64
        - arm64
        - ppc64el
        - s390x
        description: Architecture which we are deploying to. Currently we do not handle
          mixed architecture deployments
        name: ARCH
    - string:
        default: ''
        description: Specify the keystone version used for this deployment. If not
          specified, we will try to find out.
        name: KEYSTONE_API_VERSION
    - string:
        default: ''
        description: ''
        name: WORKSPACE
    - choice:
        choices:
        - ruxton
        - icarus
        - s390x
        description: ''
        name: CLOUD_NAME
    pipeline-scm:
      lightweight-checkout: true
      scm:
      - git:
          branches:
          - '*/admcleod_test'
          url: https://github.com/openstack-charmers/bot-control.git
      script-path: ./config/pipelines-mosci/4_full_cloud_configure/Jenkinsfile.groovy
    project-type: pipeline
    properties:
    - raw:
        xml: |
          <com.sonyericsson.rebuild.RebuildSettings plugin="rebuild@1.27">
          <autoRebuild>false</autoRebuild>
          <rebuildDisabled>false</rebuildDisabled>
          </com.sonyericsson.rebuild.RebuildSettings>
    - raw:
        xml: |
          <hudson.plugins.throttleconcurrents.ThrottleJobProperty plugin="throttle-concurrents@2.0.1">
          <maxConcurrentPerNode>1</maxConcurrentPerNode>
          <maxConcurrentTotal>0</maxConcurrentTotal>
          <categories class="java.util.concurrent.CopyOnWriteArrayList" />
          <throttleEnabled>true</throttleEnabled>
          <throttleOption>project</throttleOption>
          <limitOneJobWithMatchingParams>false</limitOneJobWithMatchingParams>
          <paramsToUseForLimit />
          </hudson.plugins.throttleconcurrents.ThrottleJobProperty>
    triggers: []
