- job:
    description: This job is typically run as a manual job with specifications of
      custom classes, but can also be used as a template for other tempest tests.
    disabled: false
    name: 'openstack test - tempest custom'
    parameters:
    - choice:
        choices:
        - ruxton
        - icarus
        - s390x
        description: ''
        name: CLOUD_NAME
    - choice:
        choices:
        - amd64
        - arm64
        - ppc64el
        - s390x
        description: ''
        name: ARCH
    - string:
        default: ''
        description: ''
        name: WORKSPACE
    - string:
        default: ''
        description: ''
        name: SLAVE_NODE_NAME
    - string:
        default: all-plugin
        description: Tempest test type
        name: TEST_TYPE
    - text:
        default: ''
        description: |-
          Specific tempest test classes to run, e.g.
          manila_tempest_tests.tests.api.admin
          manila_tempest_tests.tests.scenario
        name: TEST_CLASSES
    - bool:
        default: true
        description: True if this is an openstack test
        name: OPENSTACK
    pipeline-scm:
      lightweight-checkout: true
      scm:
      - git:
          branches:
          - '*/admcleod_test'
          url: https://github.com/openstack-charmers/bot-control.git
      script-path: ./config/pipelines-mosci/openstack_tests/tempest/Jenkinsfile.groovy
    project-type: pipeline
    properties:
    - raw:
        xml: |
          <com.sonyericsson.rebuild.RebuildSettings plugin="rebuild@1.27">
          <autoRebuild>false</autoRebuild>
          <rebuildDisabled>false</rebuildDisabled>
          </com.sonyericsson.rebuild.RebuildSettings>
    - raw:
        xml: |
          <hudson.plugins.throttleconcurrents.ThrottleJobProperty plugin="throttle-concurrents@2.0.1">
          <maxConcurrentPerNode>0</maxConcurrentPerNode>
          <maxConcurrentTotal>0</maxConcurrentTotal>
          <categories class="java.util.concurrent.CopyOnWriteArrayList" />
          <throttleEnabled>false</throttleEnabled>
          <throttleOption>project</throttleOption>
          <limitOneJobWithMatchingParams>false</limitOneJobWithMatchingParams>
          <paramsToUseForLimit />
          </hudson.plugins.throttleconcurrents.ThrottleJobProperty>
    triggers: []
